server:
  ipAddress: 127.0.0.1
  port: 9001
  servlet: 
    contextpath:    
        
spring:
  application:
    name: service-eis-base
  devtools: 
    restart: 
      enabled: true
  datasource:
    #url: jdbc:mysql://192.166.11.240:3306/eis?characterEncoding=utf8&amp;useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/yqcs?characterEncoding=utf8&amp;useSSL=false
    #url: jdbc:mysql://localhost:3306/zwy
    username: root
    password: root
    #password: Qazwsx123!
    #url: jdbc:mysql://172.28.31.145:3306/sscsi_eis
    driver-class-name: com.mysql.jdbc.Driver
    #初始化大小
    initialSize: 1
    #最小空閒
    minIdle: 5
    #最大連接數
    maxActive: 50
    #最大等待時間
    maxWait: 60000
    #最小生存時間
    minEvictableIdleTimeMillis: 25200000

prolog: 
  resend: 
     resendcount: 10
  debug: 
     debugMode: 1
  apidoc: #api文档配置文件
    title: 用户服务
    basePackage: com.prolog.eis
    description: 用户服务
    version: 1.0
  dao: 
    dialect: mysql
    pagehelper: #pagehelper分页插件配置
      helperDialect: ${prolog.dao.dialect}
      reasonable: true
      supportMethodsArguments: true
      pageSizeZero: false
      params: count=countSql
    #公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
    mybatis:
      typeAliasesPackage: com.prolog.eis.model
      mapperLocations: classpath:mappers/*.xml
      
  web: 
    multipart:  #文件上传配置
      maxFileSize: 100MB
      maxRequestSize: 100MB

      
  